#!/bin/bash

set -eu

VERSION=$(cat VERSION)

if docker manifest inspect maguirebrendan/random:$VERSION > /dev/null 2>&1 ; then
    echo "Image with version $VERSION already exists"
    exit 1
fi

docker build -t maguirebrendan/random:$VERSION .
docker build -t maguirebrendan/random:latest .

docker login --username maguirebrendan
docker push maguirebrendan/random:$VERSION
docker push maguirebrendan/random:latest
