name: build

on:
  push:
    branches:
      - main


jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Version tag
        id: versioning
        run: |
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          image: maguirebrendan/random
          push: true
          platforms: linux/amd64,linux/arm64
          tags:
            ${{ steps.versioning.outputs.version }},latest

